name: Deploy app
on:
  push:
  branches:
    - 'master'
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: npm install
      - name: Launch tests
        run: npm run test
  deploy:
    name: Build dependency
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Build dependency
        run: npm run build
